// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olhdcicquehastcwvieu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9saGRjaWNxdWVoYXN0Y3d2aWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzI5MDksImV4cCI6MjA2MzI0ODkwOX0.hRmOjxiNQ_p5HFeFjpboHW6jV-Dkki2NWfmL6GyUcBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);